### ISSUE TITLE
Machine Hour Rate Button not showing on 1.4.3

### ISSUE THREAD

**Issue by Antonio36996** [AndreasReitberger/3D-Print-Cost-Calculator#10]
Hi! I upgraded to 1.4.3 but I had to downgrade to 1.4.2 because the Machine Hour Rate Button on the Sidebar is missing, and even trying to change the configs from the printers menu is not working.
Thanks!

**Comment by AndreasReitberger** [comment]
Hi @Antonio36996 
Thanks for your bug report. Can you share some further information or better screenshots?
I just tried to edit a printer from the menu, and it worked on my end.

What you can try is, to uninstall 1.4.2, go to your C-drive and delete the folder
```shell
C:\Program Files\3D Print Cost Calculator 2.0
```

Maybe some stuff haven't been deleted through the uninstall assistant.
Then start a fresh installation of 1.4.3. Your database and settings are save.

Thank you!

**Comment by Antonio36996** [comment]
Hi, I tried what you suggested, the old directory is being deleted fine, this is the view that I see from the 1.4.3 version.
![image](https://github.com/AndreasReitberger/3D-Print-Cost-Calculator/assets/66578721/6aaed2f4-32d2-4159-9602-94ae5e843ff6)

And this other ones are taken from the 1.4.2
![image](https://github.com/AndreasReitberger/3D-Print-Cost-Calculator/assets/66578721/7af2cbf1-db01-43a1-adf9-cb4a806f7f43)

As you see the sidebar button is not showing in 1.4.3, thanks!

**Comment by Antonio36996** [comment]
I just checked the 1.4.3 settings and the Machine Hour Rate Calculator was hidden in the sidebar🤦‍♂️.
Everything working fine now, but I think in previous versions I could edit the Machine Hour Rate directly from the 3D Printers Menu, correct me if I'm wrong, if not, it would be a nice feature, thanks!

![image](https://github.com/AndreasReitberger/3D-Print-Cost-Calculator/assets/66578721/79508816-84f2-445d-a983-d7d1bfc7e37b)

**Comment by AndreasReitberger** [comment]
Hi @Antonio36996 
Thanks for the update. That was my second guess to check the settings.
I'm glad that it is working now.

I also will check the editing of the `HourlyMachineRate` in the printer edit dialog. As far as I can remember, editing was not possible here. However, in older versions, you could specify a fixed value for the rate. This has been removed due to database migraton.

I'll see what I can improve here :) Thanks!
