### ISSUE TITLE
Can't delete profiles

### ISSUE THREAD

**Issue by Antonio36996** [AndreasReitberger/3D-Print-Cost-Calculator#5]
There's no button to delete the profiles

**Comment by AndreasReitberger** [comment]
Hi @Antonio36996 
That's a good point. I'll log the issue in the private repo and fix it with 1.4.0

Thanks for letting me know

**Comment by AndreasReitberger** [comment]
Fixed in 

- [x] https://github.com/AndreasReitberger/3dPrintCostCalculatorPro/issues/125
