### ISSUE TITLE
Error when overwriting profiles

### ISSUE THREAD

**Issue by Antonio36996** [AndreasReitberger/3D-Print-Cost-Calculator#6]
Sometimes the modifications are saved but the error shows everytime I save a profile.

![image](https://github.com/AndreasReitberger/3D-Print-Cost-Calculator/assets/66578721/df322109-f2bb-4da4-82e2-707a183b2123)

**Comment by AndreasReitberger** [comment]
Hi @Antonio36996,

thanks for the second report. I tried to reproduce the issue on my end, however I do not get any exception when editing a profile.
Can you provide me the steps you did that this error occurred?

**Comment by Antonio36996** [comment]
Making any change on the calculation and overwritting the profile.
Is possible that might be that the calculation name is the same on the old profile and the new profile?
Also I have a few calculations in the historic that have the same name.

**Comment by AndreasReitberger** [comment]
Hi @Antonio36996 
Thanks for the details. I was able to reproduce the issue on my end now.
This is fixed already and will be released in `1.4.0`.

Thanks for letting me know, once again!

Private tracking:
- [x] https://github.com/AndreasReitberger/3dPrintCostCalculatorPro/issues/128
