### ISSUE TITLE
GCode Setting not saving

### ISSUE THREAD

**Issue by Antonio36996** [AndreasReitberger/3D-Print-Cost-Calculator#8]
The GCode settings profiles don't save when I exit the setting tab

![image](https://github.com/AndreasReitberger/3D-Print-Cost-Calculator/assets/66578721/42eb7f50-fcdd-4c07-9843-e65fed371cc4)
![image](https://github.com/AndreasReitberger/3D-Print-Cost-Calculator/assets/66578721/57f10e05-fc5c-4d4e-bed9-2b45cca7595c)

**Comment by Antonio36996** [comment]
This issue might be related, the weight shows -1 g in every file
![image](https://github.com/AndreasReitberger/3D-Print-Cost-Calculator/assets/66578721/bfd05e60-c26b-429c-ab28-3ecc96f24ed4)

**Comment by AndreasReitberger** [comment]
@Antonio36996 
Thanks for reporting this bug. I already have fixed this and will be released also with `1.4.0`.

Private tracking:
- [x] https://github.com/AndreasReitberger/3dPrintCostCalculatorPro/issues/130

However the "-1g" is not an issue, this is on purpose. If reading a gcode, we focus only on the `Volume`. The `Weight` is calculated later using the `Density` of the selected material(s).
This ensures that the weight is as accurate as possible.

The `Weight` is only used if the user provides a `Weight` in the manual print job info dialog.
Hope this clarifies it.
