### ISSUE TITLE
1.4.0 won't open

### ISSUE THREAD

**Issue by Antonio36996** [AndreasReitberger/3D-Print-Cost-Calculator#9]
I installed the windowsdesktop-runtime-7.0.5, but the new version does not open in desktop, it keeps running in background, if I try to open it again it just runs another background task, but it never opens
![image](https://github.com/AndreasReitberger/3D-Print-Cost-Calculator/assets/66578721/21d91c5f-d4c1-4475-b03a-6c1d29735a9e)

**Comment by AndreasReitberger** [comment]
What OS are you running? Windows 10?
Can you check the Windows Event viewer? Is there anything logged for the `PrintCostCalculator3d.exe`?
Please see here: https://andreas-reitberger.de/en/docs/3d-druckkosten-kalkulator/troubleshooting/fehlerlog-finden-und-auswerten/

**Comment by Antonio36996** [comment]
Is not logging anything, those logs are from 1.3.9 version, and the Windows Event Viewer is not showing any error, I closed and opened the program several times and nothing, 
![image](https://github.com/AndreasReitberger/3D-Print-Cost-Calculator/assets/66578721/0d4a4901-0c95-4bc5-84cc-cfedd4a641f1)

As you can see, if I try to open it without killing the process it keeps adding new processes in the background
![image](https://github.com/AndreasReitberger/3D-Print-Cost-Calculator/assets/66578721/b04634ea-9b98-41d6-b2c1-92e6828f3e2f)

**Comment by AndreasReitberger** [comment]
OK, thanks for sharing. This is indead a strange behaviour. It works fine on my end, I need to test further computers in order to reproduce this issue on my end. Can you do a clean restart and try to start the desktop icon as admin? (Right mouse click, run as administartor) just to be sure?

Thanks!

**Comment by Antonio36996** [comment]
I tried to restart, reinstall windowsdesktop-runtime-7.0.5, and start as administator, but still won't open.
The 1.3.9 version does open as usual.

**Comment by AndreasReitberger** [comment]
Thanks for trying. I need to investigate this behaviour and will come back to you. Sorry for any troubles caused by this. But for now, the only solution I have to suggest is to stay on 1.3.9.

I'll keep you posted.

**Comment by AndreasReitberger** [comment]
Hi @Antonio36996 
I guess I found the problem. Would you mind if you tried the following installer? 

Please proceed following steps.

1. Uninstall the old version
2. Go to `C:\Program Files\` and delete the folder `3D Print Cost Calculator 2.0` (if still there after uninstalling)
3. Install the attached version


[PrintCostCalculator3d_v1.4.0-beta.zip](https://github.com/AndreasReitberger/3D-Print-Cost-Calculator/files/11650275/PrintCostCalculator3d_v1.4.0-beta.zip)

**Comment by Antonio36996** [comment]
Yess! Now opens perfectly, thanks for the hard work!

**Comment by AndreasReitberger** [comment]
Perfect! Thanks for testing :) I'll ship this then as next release.
You're welcome 👍🏻
